#!/usr/bin/env node
/**
 * Builds the UI library (src/ui) as a standalone package. It is the input of /design-sync, which uploads
 * the components to Claude Design (see .design-sync/NOTES.md).
 *
 *   dist-ui/index.js       ES module of every export of src/ui/index.ts; React stays external
 *   dist-ui/index.css      both directions' web fonts (@import), the design tokens, the element base
 *                          styles and every component's styles
 *   dist-ui/types/         declarations; types/src/ui/index.d.ts is the entry
 *   dist-ui/package.json   name, version and entry points
 *
 * Usage: npm run build:ui
 */
import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'dist-ui');
const THEMES_DIR = path.join(ROOT, 'design/tokens/themes');
const FONTS_KEY = 'hu.stiletdekor.fonts';

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// 1. JavaScript, and the component CSS the modules import (esbuild writes it next to index.js).
await build({
  entryPoints: [path.join(ROOT, 'src/ui/index.ts')],
  outfile: path.join(OUT, 'index.js'),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  jsx: 'automatic',
  external: ['react', 'react-dom', 'react/jsx-runtime', 'react-dom/client'],
  legalComments: 'none',
  logLevel: 'warning',
});

// 2. One stylesheet: font @imports first (CSS requires them before any rule), then tokens, base, components.
const fontImports = fs
  .readdirSync(THEMES_DIR)
  .filter((f) => f.endsWith('.tokens.json'))
  .sort()
  .map((f) => JSON.parse(fs.readFileSync(path.join(THEMES_DIR, f), 'utf8')).$extensions?.[FONTS_KEY])
  .filter(Boolean)
  .map((href) => `@import url("${href}");`);
const componentCss = path.join(OUT, 'index.css');
fs.writeFileSync(
  componentCss,
  [
    '/* Stilet UI: generated by scripts/build-ui.mjs from src/styles and src/ui. */',
    ...fontImports,
    '',
    fs.readFileSync(path.join(ROOT, 'src/styles/tokens.css'), 'utf8'),
    fs.readFileSync(path.join(ROOT, 'src/styles/base.css'), 'utf8'),
    fs.readFileSync(componentCss, 'utf8'),
  ].join('\n'),
);

// 3. Declarations. The repo's tsconfig resolves "@/…" to src/; the emitted files get relative paths instead,
// so the declaration tree stands on its own.
const tsconfig = path.join(OUT, 'tsconfig.json');
fs.writeFileSync(
  tsconfig,
  JSON.stringify({
    extends: '../tsconfig.json',
    include: ['../src/ui/**/*.ts', '../src/ui/**/*.tsx'],
    exclude: ['../src/ui/**/*.test.ts', '../src/ui/**/*.test.tsx', '../src/ui/test-setup.ts'],
    compilerOptions: {
      noEmit: false,
      declaration: true,
      emitDeclarationOnly: true,
      rootDir: '..',
      outDir: 'types',
      // The CSS imports are esbuild's business; Astro's type declarations for them are not loaded here.
      noUncheckedSideEffectImports: false,
    },
  }),
);
execFileSync(process.execPath, [path.join(ROOT, 'node_modules/typescript/bin/tsc'), '-p', tsconfig], { stdio: 'inherit' });
fs.rmSync(tsconfig);

const typesDir = path.join(OUT, 'types');
const srcTypes = path.join(typesDir, 'src');
(function relink(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) relink(file);
    else if (entry.name.endsWith('.d.ts')) {
      const text = fs.readFileSync(file, 'utf8').replace(/(["'])@\/([^"']+)\1/g, (_, quote, target) => {
        let rel = path.relative(path.dirname(file), path.join(srcTypes, target)).split(path.sep).join('/');
        if (!rel.startsWith('.')) rel = `./${rel}`;
        return `${quote}${rel}${quote}`;
      });
      fs.writeFileSync(file, text);
    }
  }
})(typesDir);

// 4. Package manifest.
const { version } = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
fs.writeFileSync(
  path.join(OUT, 'package.json'),
  `${JSON.stringify(
    {
      name: '@stiletdekor/ui',
      version,
      private: true,
      type: 'module',
      module: './index.js',
      types: './types/src/ui/index.d.ts',
      style: './index.css',
      sideEffects: ['*.css'],
      peerDependencies: { react: '>=19', 'react-dom': '>=19' },
    },
    null,
    2,
  )}\n`,
);

const kb = (f) => `${(fs.statSync(path.join(OUT, f)).size / 1024).toFixed(0)} kB`;
console.log(`dist-ui: index.js ${kb('index.js')}, index.css ${kb('index.css')}, types/src/ui/index.d.ts`);
