// Bindings and vars of the Worker (see wrangler.jsonc).
//
// Runtime types (D1Database, R2Bucket, Fetcher, ExecutionContext, the `cloudflare:workers` module…)
// come from worker-configuration.d.ts, generated by `npm run cf-typegen`
// (`wrangler types --include-env=false`) for the compatibility date/flags in wrangler.jsonc.
// The Env shape is declared here by hand so vars are plain strings rather than literal types.
//
// Access (this adapter version removed Astro.locals.runtime.env):
//   import { env } from 'cloudflare:workers';
//   env.DB, env.UPLOADS, env.PUBLIC_SITE_ENV …
// Keep in sync with wrangler.jsonc and .dev.vars.example.

declare namespace Cloudflare {
  interface Env {
    /** D1: orders, quote requests, upload metadata. */
    DB: D1Database;
    /**
     * R2: customer uploads (artwork, photos, 3D files). Never public.
     * Not bound yet (R2 is not enabled on the account, see wrangler.jsonc); make it required again
     * when the binding is restored.
     */
    UPLOADS?: R2Bucket;
    /** Static assets of the site; used by the Astro adapter. */
    ASSETS: Fetcher;
    /** "dev" for the dev sites (main branch), Previews and local dev; "production" for the live site. */
    PUBLIC_SITE_ENV: 'dev' | 'production';
    /** Design direction of this deployment: "neon-muhely" (dev site A), "galeria-editorial" (dev site B) or "merolap" (C, local only). */
    SITE_THEME: string;
    /** Where new order and quote notifications are sent. */
    ORDER_NOTIFY_EMAIL: string;
    /** Comma-separated extra origins allowed for POST /api/* besides the site's own origin. */
    ALLOWED_ORIGINS: string;
    /** Rate limiter of the callback form: at most 5 posts per visitor per minute (wrangler.jsonc "ratelimits"). */
    CALLBACK_LIMITER: RateLimit;
    /**
     * Email Service send binding for the workshop's notifications. Not bound yet: it needs the stiletdekor.hu
     * domain on Cloudflare (README, "Visszahívás és értesítő e-mailek"). Until then the e-mails go to the log.
     */
    EMAIL?: SendEmail;
    /** Sender address of the notifications, on the onboarded domain (e.g. ertesito@stiletdekor.hu); empty until then. */
    NOTIFY_FROM_EMAIL: string;
    /** Cloudflare Web Analytics site token; empty: no beacon. */
    CF_BEACON_TOKEN: string;
  }
}

// Global alias used by the adapter's handler types and by `ExportedHandler<Env>`.
interface Env extends Cloudflare.Env {}
